version: '3'
services:
  postgres:
    image: postgres:11.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=klusterivilkku
    ports:
      - '5432:5432'
